apiVersion: v1
kind: Service
metadata:
  name: chat
spec:
  # NodePort 타입을 사용하여 외부 접근을 허용합니다.
  type: NodePort
  selector:
    app: mini-discord-chat
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 # NodePort 범위 예시: 30000-32767
