apiVersion: v1
kind: Service
metadata:
  name: chat
spec:
  type: NodePort
  selector:
    app: chat
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 # NodePort 범위 예시: 30000-32767
